### ISSUE TITLE
Why do we need to decode second JSON?

### ISSUE THREAD

**Issue by Spuxy** [tsawler/go-microservices#3]
Hey ! first of all, I love ur course. 
So far so good but im at start when we implement `authentication-service` but im worried why do we need check  this ?
Based on this [answer](https://stackoverflow.com/questions/21197239/decoding-json-using-json-unmarshal-vs-json-newdecoder-decode) I assume that we read the whole buffer (the whole JSON of request) and we read that so the second call `Decode()` is unnecessary, is it ?
https://github.com/tsawler/go-microservices/blob/301cd369d52951cfdd3c991a44ae9b44ba42aa36/broker-service/cmd/api/helpers.go#L27

**Comment by tsawler** [comment]
Hi:

No, it's not. This is to ensure that the posted data only includes one JSON file. Sorry for the delay, but I normally only check for questions in the Q&A section, so it's probably better to post questions there.
